### PR TITLE
Module creation

### PR DESCRIPTION
**Pull request by Jordy1311**

### CODE REVIEW

**Comment by Jordy1311** [comment]
@suessflorian, I am having a right crap time with my first module - GraphStateCtrl.. 😂 can you please take a look?

I have declared a var called graphState (_graphState inside the module to show it is private), made a function to init graphState, returned this function and object as described by Traversy but now i cant call/log either the function or the object outside of the module even though they have been returned??

**Comment by suessflorian** [comment]
Ah you've attached them to the const, try GraphStateCtrl.initGraph(0)

**Comment by Jordy1311** [comment]
Okay ignore me haha! I swear I tried this but I can't have because I can get it to work now. I must have been having a hard week with a bit of new stuff to do. I'll continue to get these modules all set up 😁

**Comment by Jordy1311** [comment]
@suessflorian I am pretty damn happy with this draw behaviour!!

**Comment by Jordy1311** [comment]
@suessflorian pending your look over and approval. Any objections or forever hold your peace?

**Comment by suessflorian** [comment]
I'll look today!

**Review by suessflorian — APPROVED** [review]
Alright, overall I'm really happy to see what you've done. I think already I can feel this codebase being a lot more readable. The `GraphStateCtrl` is definitely the standout. You look at it and it's immediately clear what it is.

I wouldn't worry too much, but if there is anything I'd probably move the `window.onload` function out of the `UICtrl`. Put it like right at the top of the file so it's easy to see what is being done initially.

```
  window.onload = () => {
    GraphStateCtrl.initGraph() // which optionally checks local storage
    UICtrl.drawGraph() // then draw this graph
  }
```

**Pull request merged**
